##### Get latest
GET http://data.fixer.io/api/latest?access_key=ce5ceb64f1a72f32ff7d9032ec81a3a5&base=GBP&symbols=ISK,SEK,USD


###### Base Access
GET http://data.fixer.io/api/latest?access_key=ce5ceb64f1a72f32ff7d9032ec81a3a5


##### Get istory
GET http://data.fixer.io/api/2020-10-30?access_key=ce5ceb64f1a72f32ff7d9032ec81a3a5

