################## Accont Info
GET https://xecdapi.xe.com/v1/account_info
Authorization: Basic kappiehf.785110797:kdidirla62k583t71kaivv075d

################## Date Rate
GET https://xecdapi.xe.com/v1/historic_rate.json/?from=USD&date=2020-11-01&to=CAD,JPY
Authorization: Basic kappiehf.785110797:kdidirla62k583t71kaivv075d

################## Historic Rate
GET https://xecdapi.xe.com/v1/historic_rate/period/?from=USD&to=CAD&start_timestamp=2020-10-01T12:00&end_timestamp=2020-10-31T12:00
Authorization: Basic kappiehf.785110797:kdidirla62k583t71kaivv075d

