## Try the default post
################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getLatestInterestAndExchangeRates"

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
	<soap:Header/>
	<soap:Body>
		<xsd:getLatestInterestAndExchangeRates>
			<languageid>en</languageid>
			<seriesid>SEKEURPMI</seriesid>
			<seriesid>SEKGBPPMI</seriesid>
			<seriesid>SECBDEPOEFF</seriesid>
			<seriesid>SEKCADPMI</seriesid>
		</xsd:getLatestInterestAndExchangeRates>   
	</soap:Body>
</soap:Envelope>

################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getInterestAndExchangeRates"

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
	<soap:Header/>
	<soap:Body>
		<xsd:getInterestAndExchangeRates>
			<searchRequestParameters>
				<aggregateMethod>D</aggregateMethod>
				<datefrom>2019-10-25</datefrom>
				<dateto>2019-11-26</dateto>
				<languageid>en</languageid>
				<min>false</min>
				<avg>true</avg>
				<max>true</max>
				<ultimo>false</ultimo>
				<searchGroupSeries>
					<groupid>11</groupid>
					<seriesid>SEKEURPMI</seriesid>
				</searchGroupSeries>
			</searchRequestParameters>
		</xsd:getInterestAndExchangeRates>
	</soap:Body>
</soap:Envelope>

################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getAllCrossNames"

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
	<soap:Header/>
	<soap:Body>
		<xsd:getAllCrossNames>
			<languageid>en</languageid>
		</xsd:getAllCrossNames>
	</soap:Body>
</soap:Envelope>


################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getCrossRatesResponse"

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Body>
		<ns2:getCrossRatesResponse xmlns:ns2="http://swea.riksbank.se/xsd">
			<return>
				<datefrom>2011-01-01</datefrom>
				<dateto>2011-03-01</dateto>
				<informationtext>The Swedish banks daily calculate a fixing rate at 9.30 a.m. according to the formula: 
					(bid+asked) / 2. At 10.05 a.m. 
					Stockholm Stock Exchange sets a joint MID-PRICE by calculating the aggregate of the banks' fixing rates.
					On the basis of the MID-PRICE it is possible to calculate exchange rates against other currencies, 
					what is known as cross rates.</informationtext>
				<groups>
					<groupid>130</groupid>
					<groupname>Currencies against Swedish kronor</groupname>
					<series>
						<seriesid1>SEK</seriesid1>
						<seriesid2>SEKNOKPMI</seriesid2>
						<seriesname>1 SEK = ? NOK</seriesname>
						<resultrows>
							<date>2011-05-23</date>
							<period>2011 Week 18</period>
							<average xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
							<value xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
						</resultrows>
					</series>
					...
				</groups>
			</return>
		</ns2:getCrossRatesResponse>
	</soap:Body>
</soap:Envelope>

################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getLatestInterestAndExchangeRates"

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
  <soap:Header />
  <soap:Body>
    <xsd:getLatestInterestAndExchangeRates>
      <languageid>en</languageid>
      <seriesid>SEKAUDPMI</seriesid>
      <seriesid>SEKCADPMI</seriesid>
      <seriesid>SEKDKKPMI</seriesid>
      <seriesid>SEKEURPMI</seriesid>
    </xsd:getLatestInterestAndExchangeRates>
  </soap:Body>
</soap:Envelope>

################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getCrossRates"

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
	<soap:Header/>
	<soap:Body>
		<xsd:getCrossRates>
			<crossRequestParameters>
				<aggregateMethod>D</aggregateMethod>
				<!--1 or more repetitions:-->
				<crossPair>
					<seriesid1>SEKEURPMI</seriesid1>
					<seriesid2>SEK</seriesid2>
				</crossPair>
				<crossPair>
					<seriesid1>SEKISKPMI</seriesid1>
					<seriesid2>SEK</seriesid2>
				</crossPair>				
				<datefrom>2020-09-20</datefrom>
				<dateto>2020-09-26</dateto>
				<languageid>en</languageid>
			</crossRequestParameters>
		</xsd:getCrossRates>
	</soap:Body>
</soap:Envelope>

################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getInterestAndExchangeGroupNames"

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
	<soap:Header/>
	<soap:Body>
		<xsd:getInterestAndExchangeGroupNames>
			<languageid>en</languageid>
		</xsd:getInterestAndExchangeGroupNames>
	</soap:Body>
</soap:Envelope>

################################################################################
POST https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint
Content-Type: application/soap+xml;charset=UTF-8;action="urn:getInterestAndExchangeNames"

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
	<soap:Header/>
	<soap:Body>
		<xsd:getInterestAndExchangeNames>
			<groupid>5</groupid>
			<languageid>sv</languageid>
		</xsd:getInterestAndExchangeNames>
	</soap:Body>
</soap:Envelope>